using Microsoft.EntityFrameworkCore.Migrations;

namespace Requests.Migrations
{
    public partial class autogeneratedIds : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
