version: "3.8"

services:

    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest       
        ports: 
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes: 
            - sqldata:/var/opt/mssql 
        networks: 
            - maestro-network
    
    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        networks: 
            - maestro-network
  
  
    identity:
        container_name: identity
        build:
            context: ./
            dockerfile: ./Server/Identity/Maestro.Identity/Dockerfile
        ports: 
            - "5002:80"
        env_file: Core/Maestro.Core/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MaestroIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - maestro-network
        depends_on:
            - data
            
    employees:
        container_name: employees
        build:
            context: ./
            dockerfile: ./Server/Employees/Maestro.Employees/Dockerfile
        ports: 
            - "5008:80"
        env_file: Core/Maestro.Core/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MaestroEmployeesDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/employees/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - maestro-network
        depends_on:
            - data
            
    requests:
        container_name: requests
        build:
            context: ./
            dockerfile: ./Server/Requests/Maestro.Requests/Dockerfile
        ports: 
            - "5004:80"
        env_file: Core/Maestro.Core/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MaestroRequestsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/requests/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - maestro-network
        depends_on:
            - data
            
    
    statistics:
        container_name: statistics
        build:
            context: ./
            dockerfile: ./Server/Statistics/Maestro.Statistics/Dockerfile
        ports: 
            - "5012:80"
        env_file: Core/Maestro.Core/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MaestroStatisticsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - maestro-network
        depends_on:
            - data
networks:
    maestro-network:

volumes:
    sqldata: